/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 15-12月-2019 16:04:22 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Course` CASCADE
;

DROP TABLE IF EXISTS `Grade` CASCADE
;

DROP TABLE IF EXISTS `Student` CASCADE
;

DROP TABLE IF EXISTS `studentcourse` CASCADE
;

DROP TABLE IF EXISTS `studentteacher` CASCADE
;

DROP TABLE IF EXISTS `Teacher` CASCADE
;

DROP TABLE IF EXISTS `teachercourse` CASCADE
;

/* Create Tables */

CREATE TABLE `Course`
(
	`Course_name` varchar(50) NULL,
	`Course_teacher` varchar(50) NULL,
	`CourseID` INT NOT NULL,
	CONSTRAINT `PK_Course` PRIMARY KEY (`CourseID` ASC)
)

;

CREATE TABLE `Grade`
(
	`Grade` FLOAT(3,0) NULL,
	`Grade_name` varchar(50) NULL,
	`GradeID` INT NOT NULL AUTO_INCREMENT,
	`StudentID` INT NOT NULL,
	CONSTRAINT `PK_Grade` PRIMARY KEY (`GradeID` ASC)
)

;

CREATE TABLE `Student`
(
	`Stu_age` TINYINT NULL,
	`Stu_name` varchar(50) NULL,
	`Stu_password` varchar(50) NULL,
	`StudentID` INT NOT NULL,
	CONSTRAINT `PK_Student` PRIMARY KEY (`StudentID` ASC)
)

;

CREATE TABLE `studentcourse`
(
	`CourseID` INT NOT NULL,
	`StudentID` INT NOT NULL,
	CONSTRAINT `PK_studentcourse` PRIMARY KEY (`CourseID` ASC, `StudentID` ASC)
)

;

CREATE TABLE `studentteacher`
(
	`TeacherID` INT NOT NULL,
	`StudentID` INT NOT NULL,
	CONSTRAINT `PK_studentteacher` PRIMARY KEY (`TeacherID` ASC, `StudentID` ASC)
)

;

CREATE TABLE `Teacher`
(
	`Tea_age` TINYINT NULL,
	`Tea_name` varchar(50) NULL,
	`Tea_password` varchar(50) NULL,
	`TeacherID` INT NOT NULL,
	CONSTRAINT `PK_Teacher` PRIMARY KEY (`TeacherID` ASC)
)

;

CREATE TABLE `teachercourse`
(
	`CourseID` INT NOT NULL,
	`TeacherID` INT NOT NULL,
	CONSTRAINT `PK_teachercourse` PRIMARY KEY (`CourseID` ASC, `TeacherID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Grade` 
 ADD CONSTRAINT `FK_Grade_Student`
	FOREIGN KEY (`StudentID`) REFERENCES `Student` (`StudentID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `studentcourse` 
 ADD CONSTRAINT `FK_studentcourse_course`
	FOREIGN KEY (`CourseID`) REFERENCES `Course` (`CourseID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `studentcourse` 
 ADD CONSTRAINT `FK_studentcourse_student`
	FOREIGN KEY (`StudentID`) REFERENCES `Student` (`StudentID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `studentteacher` 
 ADD CONSTRAINT `FK_studentteacher_teacher`
	FOREIGN KEY (`TeacherID`) REFERENCES `Teacher` (`TeacherID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `studentteacher` 
 ADD CONSTRAINT `FK_studentteacher_student`
	FOREIGN KEY (`StudentID`) REFERENCES `Student` (`StudentID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `teachercourse` 
 ADD CONSTRAINT `FK_teachercourse_course`
	FOREIGN KEY (`CourseID`) REFERENCES `Course` (`CourseID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `teachercourse` 
 ADD CONSTRAINT `FK_teachercourse_teacher`
	FOREIGN KEY (`TeacherID`) REFERENCES `Teacher` (`TeacherID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
