/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 29-12月-2019 17:48:25 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Admin` CASCADE
;

DROP TABLE IF EXISTS `Classes` CASCADE
;

DROP TABLE IF EXISTS `Dean` CASCADE
;

DROP TABLE IF EXISTS `Grade` CASCADE
;

DROP TABLE IF EXISTS `Instructor` CASCADE
;

DROP TABLE IF EXISTS `Student` CASCADE
;

DROP TABLE IF EXISTS `Teacher` CASCADE
;

/* Create Tables */

CREATE TABLE `Admin`
(
	`Admin_id` INT NULL,
	`Admin_password` varchar(50) NULL,
	`AdminID` INT NOT NULL,
	CONSTRAINT `PK_Admin` PRIMARY KEY (`AdminID` ASC)
)

;

CREATE TABLE `Classes`
(
	`Class_name` varchar(30) NULL,
	`Class_num` INT NULL,
	`ClassesID` INT NOT NULL,
	CONSTRAINT `PK_Classes` PRIMARY KEY (`ClassesID` ASC)
)

;

CREATE TABLE `Dean`
(
	`Dean_name` varchar(30) NULL,
	`Dean_password` varchar(50) NULL,
	`DeanID` INT NOT NULL,
	CONSTRAINT `PK_Dean` PRIMARY KEY (`DeanID` ASC)
)

;

CREATE TABLE `Grade`
(
	`Grade` DOUBLE(10,2) NULL,
	`Grade_end` DOUBLE(10,2) NULL,
	`Grade_middle` DOUBLE(10,2) NULL,
	`Grade_name` varchar(30) NULL,
	`Grade_normal` DOUBLE(10,2) NULL,
	`GradeID` INT NOT NULL,
	`StudentID` INT NOT NULL,
	CONSTRAINT `PK_Grade` PRIMARY KEY (`GradeID` ASC)
)

;

CREATE TABLE `Instructor`
(
	`Instr_name` varchar(30) NULL,
	`Instr_password` varchar(50) NULL,
	`InstructorID` INT NOT NULL,
	CONSTRAINT `PK_Instructor` PRIMARY KEY (`InstructorID` ASC)
)

;

CREATE TABLE `Student`
(
	`Stu_name` varchar(30) NULL,
	`Stu_password` varchar(50) NULL,
	`StudentID` INT NOT NULL,
	`ClassesID` INT NOT NULL,
	CONSTRAINT `PK_Student` PRIMARY KEY (`StudentID` ASC)
)

;

CREATE TABLE `Teacher`
(
	`Tea_name` varchar(30) NULL,
	`Tea_password` varchar(50) NULL,
	`TeacherID` INT NOT NULL,
	CONSTRAINT `PK_Teacher` PRIMARY KEY (`TeacherID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Grade` 
 ADD CONSTRAINT `FK_Grade_Student`
	FOREIGN KEY (`StudentID`) REFERENCES `Student` (`StudentID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Student` 
 ADD CONSTRAINT `FK_Student_Classes`
	FOREIGN KEY (`ClassesID`) REFERENCES `Classes` (`ClassesID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
